name: khalti_flutter
description: Khalti Payment Gateway
version: 0.0.1+1
homepage: https://khalti.com
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/khalti-flutter-sdk/issues
repository: https://github.com/khalti/khalti-flutter-sdk/tree/master/packages/khalti_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  khalti:
    path: ../khalti
  url_launcher: ^6.0.12

flutter:
  assets:
    - assets/payment/
    - assets/error/
    - assets/logo/