name: khalti
description: Khalti Payment Gateway
version: 0.0.2
homepage: https://khalti.com
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/khalti-flutter-sdk/issues
repository: https://github.com/khalti/khalti-flutter-sdk/tree/master/packages/khalti

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.1.0
  http: ^0.13.4
  khalti_core:
    path: ../khalti_core
  package_info_plus: ^1.2.1